name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: oscaralcocebaVass/oscaralcocebaVass.github.io@v1.0.0
      with:
        install_command: yarn install
        build_command: yarn run build-storybook